behaviors:
  Agent Controller:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2024
      buffer_size: 20240
      learning_rate: 0.0005
      beta: 0.002
      epsilon: 0.4
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    init_path: "Models/curriculum02/Agent Controller/checkpoint.pt"
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 14000000
    time_horizon: 1000
    summary_freq: 30000